{
 "title": "Hadoop HDFS FSImage",
 "description": "Used with Prometheus Hadoop HDFS FSImage Exporter in kubernetes",
 "tags": [
  "hdfs",
  "fsimage"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "user_name",
    "query": "label_values(fsimage_user_dirs,user_name)"
   },
   {
    "name": "group_name",
    "query": "label_values(fsimage_group_dirs,group_name)"
   },
   {
    "name": "instance",
    "query": "label_values(fsimage_group_dirs,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "FSImage global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Quantidade de diretórios",
   "type": "graph",
   "description": "Number of directories.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(fsimage_dirs)" }
   ]
  },
  {
   "title": "Quantidade de arquivos",
   "type": "graph",
   "description": "Quantidade de arquivos",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(fsimage_fsize_count)" }
   ]
  },
  {
   "title": "Quantidade de réplicas (arquivos)",
   "type": "graph",
   "description": "Overall file replication",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(fsimage_replication_sum)" }
   ]
  },
  {
   "title": "Tamanho Total Arquivos",
   "type": "graph",
   "description": "Overall file size distribution",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "max(fsimage_fsize_sum)" }
   ]
  },
  {
   "title": "Quantidade de blocos HDFS",
   "type": "graph",
   "description": "Number of blocks.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(fsimage_blocks)" }
   ]
  },
  {
   "title": "Quantidade de blocos HDFS",
   "type": "graph",
   "description": "Number of blocks.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(fsimage_blocks)" }
   ]
  },
  {
   "title": "User/Group",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Quantidade de diretórios por usuário",
   "type": "graph",
   "description": "Number of directories.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(fsimage_user_dirs{user_name=~\"$user_name\"})",
     "legendFormat": "$user_name"
    }
   ]
  },
  {
   "title": "Quantiade de blocos por usuário",
   "type": "graph",
   "description": "Number of blocks.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(fsimage_user_blocks{user_name=~\"$user_name\"})",
     "legendFormat": "$user_name"
    }
   ]
  },
  {
   "title": "Quantidade de diretórios por grupo usuário",
   "type": "graph",
   "description": "Number of directories.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(fsimage_group_dirs{group_name=~\"$group_name\"})",
     "legendFormat": "$group_name"
    }
   ]
  },
  {
   "title": "Quantiade de blocos por grupo usuário",
   "type": "graph",
   "description": "Number of blocks.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(fsimage_group_blocks{group_name=~\"$group_name\"})",
     "legendFormat": "$group_name"
    }
   ]
  }
 ]
}